using System.Text.Json;
using HybridSearch.Broker.Experiments;

namespace HybridSearch.Broker.Tests;

/// <summary>
/// ExperimentAssigner against vectors generated by the Python mirror
/// (py/hybridsearch/clicks/events.py). Offline analysis of an A/B log recomputes each session's
/// arm in Python; this test is what makes that recomputation trustworthy.
/// </summary>
public class AssignmentGoldenTests
{
    public static IEnumerable<object[]> Vectors()
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(Path.Combine(TestPaths.RepoRoot, "tests", "golden", "assignment.json")));
        foreach (var v in doc.RootElement.GetProperty("vectors").EnumerateArray())
            yield return [v.GetProperty("salt").GetString()!, v.GetProperty("sessionId").GetString()!,
                          v.GetProperty("allocation").GetDouble(), v.GetProperty("bucket").GetUInt32(),
                          v.GetProperty("assignment").ValueKind == JsonValueKind.Null ? "none" : v.GetProperty("assignment").GetString()!];
    }

    [Theory]
    [MemberData(nameof(Vectors))]
    public void MatchesPythonMirror(string salt, string sessionId, double allocation, uint bucket, string assignment)
    {
        uint b = ExperimentAssigner.Bucket(salt, sessionId);
        Assert.Equal(bucket, b);
        string got = !ExperimentAssigner.IsEnrolled(allocation, b) ? "none"
            : ExperimentAssigner.Arm(salt, sessionId) == Variant.Control ? "control" : "treatment";
        Assert.Equal(assignment, got);
    }
}
