#!/usr/bin/env python
"""Writes tests/golden/interleaving.json: deterministic team-draft interleaving cases
shared by the Python implementation (py/hybridsearch/clicks/interleave.py) and the C#
broker. Cases 1-7 have hand-derived expectations that are asserted against the Python
implementation before the file is written; the rest are generated by it.

Usage: .venv/bin/python scripts/m9_make_golden.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "py"))

from hybridsearch.clicks.interleave import enumerate_team_draft, team_draft, team_draft_credit  # noqa: E402

ALGORITHM = [
    "Team-draft interleaving (Radlinski, Kurup & Joachims, CIKM 2008), exact variant:",
    "I = [], sizeA = sizeB = 0.",
    "Loop while len(I) < k and at least one of rankingA / rankingB has a document not in I:",
    "  if sizeA < sizeB: A picks; elif sizeB < sizeA: B picks;",
    "  else (sizes equal): consume the next value of `coins`; true => A picks, false => B picks.",
    "  The picking team appends its highest-ranked document not already in I, and that position belongs to it.",
    "  If the picking team has no document left, the other team picks instead (and owns the position);",
    "  a coin that was consumed is not re-flipped.",
    "Credit: each clicked position counts for the team that owns it; more clicks wins; equal (incl. 0-0) is a tie.",
    "Coins are consumed ONLY when sizes are equal, so an implementation drawing from an RNG must draw exactly then.",
]

# (name, A, B, k, coins, expected interleaved, expected teams, coins consumed, click tests)
HAND = [
    ("disjoint_a_first", [1, 2, 3, 4], [5, 6, 7, 8], 4, [True, True],
     [1, 5, 2, 6], "ABAB", 2,
     [([1], (1, 0, "A")), ([5, 6], (0, 2, "B")), ([1, 5], (1, 1, "tie")), ([], (0, 0, "tie"))]),
    ("disjoint_b_first", [1, 2, 3, 4], [5, 6, 7, 8], 4, [False, False],
     [5, 1, 6, 2], "BABA", 2,
     [([1, 2], (2, 0, "A")), ([5], (0, 1, "B"))]),
    ("identical_rankings", [1, 2, 3, 4], [1, 2, 3, 4], 4, [True, False],
     [1, 2, 3, 4], "ABBA", 2,
     [([1], (1, 0, "A")), ([2, 3], (0, 2, "B")), ([1, 4], (2, 0, "A"))]),
    ("overlap_with_duplicates", [1, 2, 3, 4, 5], [2, 1, 6, 3, 7], 5, [False, True, True],
     [2, 1, 3, 6, 4], "BAABA", 3,
     [([2], (0, 1, "B")), ([1, 3], (2, 0, "A")), ([2, 6, 4], (1, 2, "B"))]),
    ("b_exhausted_a_fills", [1, 2, 3, 4, 5, 6], [1], 5, [True],
     [1, 2, 3, 4, 5], "AAAAA", 1,
     [([5], (1, 0, "A"))]),
    ("k_exceeds_union", [1, 2], [2, 3], 10, [True, True],
     [1, 2, 3], "ABB", 2,
     [([3], (0, 1, "B")), ([1, 2], (1, 1, "tie"))]),
    ("odd_k", [10, 20, 30], [30, 20, 10], 3, [False, True],
     [30, 10, 20], "BAA", 2,
     [([20], (1, 0, "A")), ([30], (0, 1, "B"))]),
]

GENERATED = [
    ("empty_b", [7, 8, 9], [], 3, [False]),
    ("empty_both", [], [], 5, []),
    ("realistic_k10", [7067032, 7067033, 1017759, 1082489, 109063, 44, 55, 66, 77, 88, 99],
     [1082489, 7067032, 12, 13, 1017759, 14, 15, 44, 16, 17], 10, [True, False, False, True, True]),
    ("k1_b_first", [1, 2], [3, 4], 1, [False]),
    ("a_prefix_of_b", [1, 2], [1, 2, 3, 4, 5], 5, [True, True, False]),
]


def case_dict(name, a, b, k, coins, clicks_tests):
    out, teams, used = team_draft(a, b, k, coins)
    return {
        "name": name,
        "rankingA": a, "rankingB": b, "k": k, "coins": coins,
        "expected": {"interleaved": out, "teams": teams, "coinsConsumed": used},
        "clickTests": [
            dict(zip(("clickedDocIds", "clicksA", "clicksB", "winner"),
                     (c, *team_draft_credit(teams, [out.index(d) for d in c]))))
            for c in clicks_tests
        ],
    }


def main():
    cases = []
    for name, a, b, k, coins, exp, exp_teams, used, clicks in HAND:
        d = case_dict(name, a, b, k, coins, [c for c, _ in clicks])
        assert d["expected"]["interleaved"] == exp, (name, d["expected"], exp)
        assert "".join(d["expected"]["teams"]) == exp_teams, (name, d["expected"]["teams"])
        assert d["expected"]["coinsConsumed"] == used, name
        for t, (_, want) in zip(d["clickTests"], clicks):
            assert (t["clicksA"], t["clicksB"], t["winner"]) == want, (name, t, want)
        d["handDerived"] = True
        cases.append(d)
    for name, a, b, k, coins in GENERATED:
        out, _, _ = team_draft(a, b, k, coins)
        clicks = [out[:1], out[-2:]] if out else [[]]
        d = case_dict(name, a, b, k, coins, clicks)
        d["handDerived"] = False
        cases.append(d)

    # full outcome distributions: a randomised implementation should match these
    # frequencies (each coin is a fair coin).
    dists = []
    for name, a, b, k in [("overlap_k4", [1, 2, 3, 4], [2, 5, 1, 6], 4), ("identical_k3", [1, 2, 3], [1, 2, 3], 3)]:
        agg: dict[str, float] = {}
        for out, teams, p in enumerate_team_draft(a, b, k):
            key = json.dumps({"interleaved": out, "teams": teams}, separators=(",", ":"))
            agg[key] = agg.get(key, 0.0) + p
        dists.append({"name": name, "rankingA": a, "rankingB": b, "k": k,
                      "outcomes": [dict(json.loads(kk), probability=v) for kk, v in sorted(agg.items())]})

    doc = {
        "description": "Golden cases for team-draft interleaving. Shared contract between "
                       "py/hybridsearch/clicks/interleave.py and the C# broker. Coins are explicit so the cases "
                       "are seed-free and deterministic. Generated by scripts/m9_make_golden.py.",
        "algorithm": ALGORITHM,
        "cases": cases,
        "distributions": dists,
    }
    path = ROOT / "tests/golden/interleaving.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(doc, indent=2) + "\n")
    print(f"wrote {path} ({len(cases)} cases, {len(dists)} distributions)")


if __name__ == "__main__":
    main()
