"""Generate engine/src/lexical/unicode_data.inc from the Unicode Character Database.

Lucene 10's StandardTokenizerImpl.jflex declares `%unicode 12.1`, so the word-break
grammar's properties come from UCD 12.1 (WordBreakProperty, Scripts, LineBreak) and
emoji-data 12.1. LowerCaseFilter calls java.lang.Character.toLowerCase(int); Java 21
implements Unicode 15.0, so the simple lowercase mapping comes from UnicodeData 15.0.

The C++ side (engine/src/lexical/tokenizer.cc) turns these bit masks into an alphabet of
equivalence classes and compiles the grammar to a DFA.

Usage: python -m hybridsearch.lexical.gen_unicode_tables [ucd_dir] [out_inc]
Files are downloaded into ucd_dir (default data/cache/unicode) if missing.
"""

from __future__ import annotations

import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SOURCES = {
    "WordBreakProperty-12.1.txt": "https://www.unicode.org/Public/12.1.0/ucd/auxiliary/WordBreakProperty.txt",
    "Scripts-12.1.txt": "https://www.unicode.org/Public/12.1.0/ucd/Scripts.txt",
    "LineBreak-12.1.txt": "https://www.unicode.org/Public/12.1.0/ucd/LineBreak.txt",
    "emoji-data-12.1.txt": "https://www.unicode.org/Public/emoji/12.1/emoji-data.txt",
    "UnicodeData-15.0.txt": "https://www.unicode.org/Public/15.0.0/ucd/UnicodeData.txt",
}

# Bit assignments. Must match engine/src/lexical/unicode_props.hpp.
BITS = {
    "WB_Format": 0, "WB_Extend": 1, "WB_ZWJ": 2, "WB_Regional_Indicator": 3,
    "WB_ALetter": 4, "WB_Hebrew_Letter": 5, "WB_Numeric": 6, "WB_Katakana": 7,
    "WB_MidLetter": 8, "WB_MidNumLet": 9, "WB_Single_Quote": 10, "WB_MidNum": 11,
    "WB_ExtendNumLet": 12, "WB_Double_Quote": 13,
    "SC_Hangul": 14, "SC_Han": 15, "SC_Hiragana": 16, "LB_SA": 17,
    "Emoji": 18, "Emoji_Modifier": 19, "Emoji_Modifier_Base": 20, "Extended_Pictographic": 21,
    "KeyCapBase": 22, "AccidentalEmoji": 23, "VS15": 24, "VS16": 25, "KeyCap": 26,
    "TagSpec": 27, "TagTerm": 28,
}
MAXCP = 0x110000


def parse_ranges(path: Path):
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        rng, val = [x.strip() for x in line.split(";")[:2]]
        if ".." in rng:
            lo, hi = (int(x, 16) for x in rng.split(".."))
        else:
            lo = hi = int(rng, 16)
        yield lo, hi, val


def main() -> None:
    ucd = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "data/cache/unicode"
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "engine/src/lexical/unicode_data.inc"
    ucd.mkdir(parents=True, exist_ok=True)
    for name, url in SOURCES.items():
        if not (ucd / name).exists():
            urllib.request.urlretrieve(url, ucd / name)

    mask = [0] * MAXCP

    def setbit(lo: int, hi: int, bit: str) -> None:
        b = 1 << BITS[bit]
        for cp in range(lo, hi + 1):
            mask[cp] |= b

    wb_names = {k[3:] for k in BITS if k.startswith("WB_")}
    for lo, hi, val in parse_ranges(ucd / "WordBreakProperty-12.1.txt"):
        if val in wb_names:
            setbit(lo, hi, "WB_" + val)
    for lo, hi, val in parse_ranges(ucd / "Scripts-12.1.txt"):
        if val in ("Hangul", "Han", "Hiragana"):
            setbit(lo, hi, "SC_" + val)
    for lo, hi, val in parse_ranges(ucd / "LineBreak-12.1.txt"):
        if val == "SA":
            setbit(lo, hi, "LB_SA")
    for lo, hi, val in parse_ranges(ucd / "emoji-data-12.1.txt"):
        if val in ("Emoji", "Emoji_Modifier", "Emoji_Modifier_Base", "Extended_Pictographic"):
            setbit(lo, hi, val)
    for c in "0123456789#*":
        setbit(ord(c), ord(c), "KeyCapBase")
    for c in (0xA9, 0xAE, 0x2122, 0x3030, 0x303D):  # (c) (R) TM, wavy dash, part alternation mark
        setbit(c, c, "AccidentalEmoji")
    setbit(0xFE0E, 0xFE0E, "VS15")
    setbit(0xFE0F, 0xFE0F, "VS16")
    setbit(0x20E3, 0x20E3, "KeyCap")
    setbit(0xE0020, 0xE007E, "TagSpec")
    setbit(0xE007F, 0xE007F, "TagTerm")

    ranges = []
    cp = 0
    while cp < MAXCP:
        m = mask[cp]
        start = cp
        while cp + 1 < MAXCP and mask[cp + 1] == m:
            cp += 1
        if m:
            ranges.append((start, cp, m))
        cp += 1

    lower = []
    for line in (ucd / "UnicodeData-15.0.txt").read_text(encoding="utf-8").splitlines():
        f = line.split(";")
        if f[13]:
            lower.append((int(f[0], 16), int(f[13], 16)))
    lower.sort()

    with out.open("w", encoding="utf-8") as o:
        o.write("// GENERATED by py/hybridsearch/lexical/gen_unicode_tables.py. Do not edit.\n")
        o.write("// Word-break grammar properties: UCD 12.1 + emoji-data 12.1 (Lucene 10 JFlex %unicode 12.1).\n")
        o.write("// Lowercase: UnicodeData 15.0 simple lowercase (java.lang.Character.toLowerCase, Java 21).\n")
        o.write(f"// {len(ranges)} property ranges, {len(lower)} lowercase pairs.\n")
        o.write("static constexpr PropRange kPropRanges[] = {\n")
        for lo, hi, m in ranges:
            o.write(f"  {{0x{lo:X}, 0x{hi:X}, 0x{m:X}u}},\n")
        o.write("};\n")
        o.write("static constexpr LowerPair kLowerPairs[] = {\n")
        for a, b in lower:
            o.write(f"  {{0x{a:X}, 0x{b:X}}},\n")
        o.write("};\n")
    print(f"wrote {out}: {len(ranges)} ranges, {len(lower)} lowercase pairs")


if __name__ == "__main__":
    main()
